import {readShareMoment} from './share-source.ts'
import {createShareSnapshot,attachShareImage,decodeSharePng,getPublicShareSnapshot,shareImageResponse,getBadgeShareStory} from './share-snapshots.ts'
const assert=(v:any,msg='assertion failed')=>{if(!v)throw new Error(msg)}
function db(){
 const tables:any={rc_config:[],rc_goals:[],rc_wards:[],rc_districts:[{id:'district',name:'Puple Sky Overlook',ward_id:'mono',active:true},{id:'center',name:'Moon',ward_id:'mono',is_centerpiece:true,active:true}],rc_player_districts:[{agent_no:'SELF',district_id:'district',status:'active',activated_at:new Date().toISOString(),baseline:{},goals:{trackGoals:[{id:'one',label:'SWIM',keys:['swim'],target:100},{id:'two',label:'Haegeum',keys:['haegeum'],target:10}],albumGoals:[],reconnect:null}}],rc_daily_activity:[{agent_no:'SELF',kst_date:'2099-01-01',track_counts:{swim:{n:50},haegeum:{n:0}}}],rc_backup_requests:[],rc_agent_charge:[{agent_no:'SELF',charged_until:new Date(Date.now()+32*3600000).toISOString()}],rc_defuse_events:[],rc_share_snapshots:[],rc_auth_attempts:[]}
 const touched:string[]=[]
 return {tables,touched,from(table:string){touched.push(table);let rows=[...(tables[table]||[])],single=false,patch:any=null,insert:any=null;const q:any={select(){return q},eq(k:string,v:any){rows=rows.filter(r=>r[k]===v);return q},neq(k:string,v:any){rows=rows.filter(r=>r[k]!==v);return q},gte(k:string,v:any){rows=rows.filter(r=>r[k]>=v);return q},gt(k:string,v:any){rows=rows.filter(r=>r[k]>v);return q},lt(){return q},in(k:string,vs:any[]){rows=rows.filter(r=>vs.includes(r[k]));return q},is(k:string,v:any){rows=rows.filter(r=>v===null?r[k]==null:r[k]===v);return q},not(k:string,_op:string,v:any){rows=rows.filter(r=>v===null?r[k]!=null:r[k]!==v);return q},order(){return q},limit(n:number){rows=rows.slice(0,n);return q},maybeSingle(){single=true;return q},update(p:any){patch=p;return q},insert(p:any){insert=p;return q},delete(){return q},then(resolve:any){if(insert){const row={created_at:new Date().toISOString(),expires_at:'2099-01-01',...insert};(tables[table]||=[]).push(row);rows=[row]}if(patch)rows.forEach(r=>Object.assign(r,patch));return Promise.resolve({data:single?rows[0]||null:rows,error:null,count:rows.length}).then(resolve)}};return q}}
}
Deno.test('badge pixels cannot be client-uploaded and another owner cannot request its Story',async()=>{
 const sb=db(),id='abcdefghijklmnopqrstuv';sb.tables.rc_share_snapshots.push({id,kind:'badge',created_by:'SELF',badge_art_id:17,expires_at:'2099-01-01',image_png:null,data:{milestonePercent:25}})
 const uploaded=await attachShareImage(sb,{agentNo:'SELF',id,png:await png()});assert(!uploaded.success);assert(sb.tables.rc_share_snapshots[0].image_png===null)
 const story=await getBadgeShareStory(sb,{agentNo:'OTHER',id});assert(!story.success)
})
function event(){return {id:'event',status:'active',target:2000,progress:628,active_from:'2026-01-01',active_until:'2099-01-01',target_kind:'track',target_label:'SWIM'}}
async function png(){
 const raw=new Uint8Array((1200*4+1)*630);const compressed=new Uint8Array(await new Response(new Blob([raw]).stream().pipeThrough(new CompressionStream('deflate'))).arrayBuffer())
 const chunk=(type:string,data:Uint8Array)=>{const out=new Uint8Array(data.length+12);const dv=new DataView(out.buffer);dv.setUint32(0,data.length);out.set(new TextEncoder().encode(type),4);out.set(data,8);let crc=0xffffffff;for(let i=4;i<out.length-4;i++){crc^=out[i];for(let b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}dv.setUint32(out.length-4,(crc^0xffffffff)>>>0);return out}
 const header=new Uint8Array(13);const v=new DataView(header.buffer);v.setUint32(0,1200);v.setUint32(4,630);header[8]=8;header[9]=6
 const parts=[new Uint8Array([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',compressed),chunk('IEND',new Uint8Array())];const bytes=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let offset=0;for(const p of parts){bytes.set(p,offset);offset+=p.length}let str='';for(const b of bytes)str+=String.fromCharCode(b);return btoa(str)
}
Deno.test('City source selects Bomb, never a district, and avoids full game-state tables',async()=>{const s=db(),result=await readShareMoment(s,'SELF','city_bomb','');assert(result.kind==='city_bomb');assert(result.hoursRemaining===32);assert(!s.touched.includes('rc_daily_activity'));assert(!s.touched.includes('rc_goals'))})
Deno.test('City routes an active attack to Red Zone; ended attacks cannot be shared as live',async()=>{const s=db();s.tables.rc_defuse_events=[event()];assert((await readShareMoment(s,'SELF','city_bomb','')).kind==='red_zone_active');s.tables.rc_defuse_events[0].active_until='2020-01-01';let rejected=false;try{await readShareMoment(s,'SELF','red_zone_active','')}catch{rejected=true}assert(rejected)})
Deno.test('District percent matches target-weighted page progress, not average goal percentages',async()=>{const s=db();const result=await readShareMoment(s,'SELF','district','district');assert(result.percent===45,JSON.stringify(result));assert(!s.touched.includes('rc_agent_charge'))})
Deno.test('Unrestored centerpiece and another player district cannot leak through sharing',async()=>{const s=db();let denied=0;for(const [agent,id] of [['OTHER','district'],['SELF','center']])try{await readShareMoment(s,agent,'district',id)}catch{denied++}assert(denied===2);s.tables.rc_player_districts[0].status='restored';assert((await readShareMoment(s,'SELF','district','center')).percent===100)})
Deno.test('Frozen image reuse survives unchanged state; changed progress creates a new snapshot',async()=>{const s=db();s.tables.rc_defuse_events=[event()];const a:any=await createShareSnapshot(s,{agentNo:'SELF',kind:'red_zone_active'});assert(a.success,JSON.stringify(a));s.tables.rc_share_snapshots[0].image_png=await png();const b:any=await createShareSnapshot(s,{agentNo:'SELF',kind:'red_zone_active'});assert(b.id===a.id&&b.imageReady);s.tables.rc_defuse_events[0].progress=800;const c:any=await createShareSnapshot(s,{agentNo:'SELF',kind:'red_zone_active'});assert(c.id!==a.id&&c.data.progress===800)})
Deno.test('Only owner can attach a validated PNG, and a published image is immutable',async()=>{const s=db();const a:any=await createShareSnapshot(s,{agentNo:'SELF',kind:'city_bomb'});const image=await png();assert(!(await attachShareImage(s,{agentNo:'OTHER',id:a.id,png:image})).success);assert((await attachShareImage(s,{agentNo:'SELF',id:a.id,png:image})).success);assert(!(await attachShareImage(s,{agentNo:'SELF',id:a.id,png:image})).success);const publicResult=await getPublicShareSnapshot(s,{id:a.id});assert(!JSON.stringify(publicResult).includes('SELF'));assert(!JSON.stringify(publicResult).includes('image_png'));const response=await shareImageResponse(s,a.id);assert(response.status===200&&response.headers.get('Content-Type')==='image/png')})
Deno.test('Malformed, oversized and corrupted PNG uploads are rejected',async()=>{const good=await png();assert(decodeSharePng(good).length>33);for(const bad of ['abc','A'.repeat(700001),good.slice(0,-8)+'AAAAAAAA']){let denied=false;try{decodeSharePng(bad)}catch{denied=true}assert(denied)}})
